services:
  trucki-api-staging:
    extends:
      file: docker-compose.yml
      service: trucki-api-base
    container_name: trucki-api-staging
    ports:
      - "127.0.0.1:8081:80"
    networks:
      - staging-network
    volumes:
      - app-logs-staging:/app/logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ConnectionStrings__LocalConnection=${STAGING_DB_CONNECTION}
      - IdentityServerSettings__DiscoveryUrl=${STAGING_DISCOVERY_URL}
      - EmailSetting__Email=${EMAIL_USERNAME}
      - EmailSetting__Password=${EMAIL_PASSWORD}
      - EmailSetting__From=${EMAIL_FROM}
      - EmailSetting__SmtpServer=${EMAIL_SMTP_SERVER}
      - EmailSetting__SmtpPort=${EMAIL_SMTP_PORT}
      - EmailSetting__UseSsl=${EMAIL_USE_SSL}
      - Cloudinary__cloudName=${CLOUDINARY_CLOUD_NAME}
      - Cloudinary__apiKey=${CLOUDINARY_API_KEY}
      - Cloudinary__apiSecret=${CLOUDINARY_API_SECRET}
      - Stripe__SecretKey=${STRIPE_TEST_SECRET_KEY}
      - Stripe__WebhookSecret=${STRIPE_TEST_WEBHOOK_SECRET}
networks:
  staging-network:
    driver: bridge
    name: trucki-staging-network
volumes:
  app-logs-staging:
    name: trucki-app-logs-staging